'use client';

import { useState } from 'react';

const LENGTH_OPTIONS = [
  { label: 'Auto', value: 0 },
    { label: '10 min', value: 600 },
      { label: '20 min', value: 1200 },
        { label: '30 min', value: 1800 },
          { label: '45 min', value: 2700 },
            { label: '60 min', value: 3600 },
            ];

            export default function DashboardPage() {
              const [prompt, setPrompt] = useState('');
                const [length, setLength] = useState(1200);
                  const [loading, setLoading] = useState(false);
                    const [projectId, setProjectId] = useState<string | null>(null);
                      const [error, setError] = useState<string | null>(null);

                        const handleGenerate = async () => {
                            if (!prompt.trim() || prompt.length < 10) {
                                  setError('Please describe your video idea'); return;
                                      }
                                          setLoading(true); setError(null);
                                              try {
                                                    const res = await fetch('/api/projects', {
                                                            method: 'POST',
                                                                    headers: { 'Content-Type': 'application/json' },
                                                                            body: JSON.stringify({ prompt: prompt.trim(), targetLengthSeconds: length, userId: 'demo-user' }),
                                                                                  });
                                                                                        const data = await res.json();
                                                                                              if (!res.ok) throw new Error(data.error);
                                                                                                    setProjectId(data.projectId);
                                                                                                        } catch (e: any) {
                                                                                                              setError(e.message);
                                                                                                                  } finally { setLoading(false); }
                                                                                                                    };
                                                                                                                    
                                                                                                                      if (projectId) {
                                                                                                                          return (
                                                                                                                                <div className="min-h-screen bg-black text-white flex items-center justify-center p-8">
                                                                                                                                        <div className="max-w-md text-center">
                                                                                                                                                  <div className="text-6xl mb-6">OK</div>
                                                                                                                                                            <h2 className="text-2xl font-bold mb-4">Video Generation Started</h2>
                                                                                                                                                                      <p className="text-gray-400 mb-6">Mateo Cruz is telling his story. This takes 15-60 minutes.</p>
                                                                                                                                                                                <div className="bg-gray-900 rounded-lg p-4 mb-6">
                                                                                                                                                                                            <p className="text-sm text-gray-500">Project ID</p>
                                                                                                                                                                                                        <p className="font-mono text-sm text-gray-300">{projectId}</p>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                            <a href={`/projects/${projectId}`} className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg inline-block">
                                                                                                                                                                                                                                        Track Progress
                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                            <button onClick={() => { setProjectId(null); setPrompt(''); }} className="ml-4 text-gray-500 hover:text-gray-300">
                                                                                                                                                                                                                                                                        Generate Another
                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                            <div className="min-h-screen bg-black text-white">
                                                                                                                                                                                                                                                                                                                  <div className="border-b border-gray-800 px-8 py-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                    <h1 className="text-xl font-bold">Inside Mateo Cruz</h1>
                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-500">Autonomous Cinematic YouTube Studio</p>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-6">
            <a href="/avatars" className="text-sm text-gray-400 hover:text-white">Avatars</a>
            <a href="/projects" className="text-sm text-gray-400 hover:text-white">My Videos</a>
          </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                          <div className="max-w-3xl mx-auto px-8 py-12">
                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-10">
                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-3xl font-bold mb-3">Create a Video</h2>
                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-400">Describe your idea. Mateo Cruz will tell the story as a cinematic long-form YouTube video.</p>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-400 mb-2">Your Idea</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={prompt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPrompt(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="e.g. A man battling depression hears knocking at the door every night, but the door is his own mind..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full bg-gray-900 border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-gray-600 resize-none focus:outline-none focus:border-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mb-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium text-gray-400 mb-2">Video Length</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-6 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {LENGTH_OPTIONS.map((opt) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button key={opt.value} onClick={() => setLength(opt.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`py-2 px-3 rounded-lg text-sm font-medium border ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                length === opt.value ? 'bg-blue-600 border-blue-600 text-white' : 'bg-gray-900 border-gray-700 text-gray-400'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }`}>{opt.label}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && <div className="mb-4 p-3 bg-red-900/30 border border-red-700 rounded-lg text-red-400 text-sm">{error}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={handleGenerate} disabled={loading || prompt.length < 10}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full py-4 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 text-white font-semibold rounded-lg text-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Starting...' : 'Generate Video'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-4 text-center text-xs text-gray-600">AI-generated content. Original stories only.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
